package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CargaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCargaAllPropertiesEquals(Carga expected, Carga actual) {
        assertCargaAutoGeneratedPropertiesEquals(expected, actual);
        assertCargaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCargaAllUpdatablePropertiesEquals(Carga expected, Carga actual) {
        assertCargaUpdatableFieldsEquals(expected, actual);
        assertCargaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCargaAutoGeneratedPropertiesEquals(Carga expected, Carga actual) {
        assertThat(expected)
            .as("Verify Carga auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCargaUpdatableFieldsEquals(Carga expected, Carga actual) {
        assertThat(expected)
            .as("Verify Carga relevant properties")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getOrdem()).as("check ordem").isEqualTo(actual.getOrdem()))
            .satisfies(e -> assertThat(e.getPlanilha()).as("check planilha").isEqualTo(actual.getPlanilha()))
            .satisfies(
                e -> assertThat(e.getPlanilhaContentType()).as("check planilha contenty type").isEqualTo(actual.getPlanilhaContentType())
            )
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getCaminho()).as("check caminho").isEqualTo(actual.getCaminho()))
            .satisfies(e -> assertThat(e.getValidado()).as("check validado").isEqualTo(actual.getValidado()))
            .satisfies(e -> assertThat(e.getTipo()).as("check tipo").isEqualTo(actual.getTipo()))
            .satisfies(e -> assertThat(e.getFormato()).as("check formato").isEqualTo(actual.getFormato()))
            .satisfies(e -> assertThat(e.getDestino()).as("check destino").isEqualTo(actual.getDestino()))
            .satisfies(e -> assertThat(e.getLinhas()).as("check linhas").isEqualTo(actual.getLinhas()))
            .satisfies(e -> assertThat(e.getChecksum()).as("check checksum").isEqualTo(actual.getChecksum()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCargaUpdatableRelationshipsEquals(Carga expected, Carga actual) {
        assertThat(expected)
            .as("Verify Carga relationships")
            .satisfies(e -> assertThat(e.getVersao()).as("check versao").isEqualTo(actual.getVersao()));
    }
}
