package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CuradoriaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuradoriaAllPropertiesEquals(Curadoria expected, Curadoria actual) {
        assertCuradoriaAutoGeneratedPropertiesEquals(expected, actual);
        assertCuradoriaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuradoriaAllUpdatablePropertiesEquals(Curadoria expected, Curadoria actual) {
        assertCuradoriaUpdatableFieldsEquals(expected, actual);
        assertCuradoriaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuradoriaAutoGeneratedPropertiesEquals(Curadoria expected, Curadoria actual) {
        assertThat(expected)
            .as("Verify Curadoria auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuradoriaUpdatableFieldsEquals(Curadoria expected, Curadoria actual) {
        assertThat(expected)
            .as("Verify Curadoria relevant properties")
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getData()).as("check data").isEqualTo(actual.getData()))
            .satisfies(e -> assertThat(e.getAnotacoes()).as("check anotacoes").isEqualTo(actual.getAnotacoes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuradoriaUpdatableRelationshipsEquals(Curadoria expected, Curadoria actual) {}
}
