package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DBConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBConfigAllPropertiesEquals(DBConfig expected, DBConfig actual) {
        assertDBConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertDBConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBConfigAllUpdatablePropertiesEquals(DBConfig expected, DBConfig actual) {
        assertDBConfigUpdatableFieldsEquals(expected, actual);
        assertDBConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBConfigAutoGeneratedPropertiesEquals(DBConfig expected, DBConfig actual) {
        assertThat(expected)
            .as("Verify DBConfig auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBConfigUpdatableFieldsEquals(DBConfig expected, DBConfig actual) {
        assertThat(expected)
            .as("Verify DBConfig relevant properties")
            .satisfies(e -> assertThat(e.getKey()).as("check key").isEqualTo(actual.getKey()))
            .satisfies(e -> assertThat(e.getHabilitado()).as("check habilitado").isEqualTo(actual.getHabilitado()))
            .satisfies(e -> assertThat(e.getVstring()).as("check vstring").isEqualTo(actual.getVstring()))
            .satisfies(e -> assertThat(e.getVbol()).as("check vbol").isEqualTo(actual.getVbol()))
            .satisfies(e -> assertThat(e.getVdate()).as("check vdate").isEqualTo(actual.getVdate()))
            .satisfies(e -> assertThat(e.getVint()).as("check vint").isEqualTo(actual.getVint()))
            .satisfies(e -> assertThat(e.getVtext()).as("check vtext").isEqualTo(actual.getVtext()))
            .satisfies(e -> assertThat(e.getVimg()).as("check vimg").isEqualTo(actual.getVimg()))
            .satisfies(e -> assertThat(e.getVimgContentType()).as("check vimg contenty type").isEqualTo(actual.getVimgContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBConfigUpdatableRelationshipsEquals(DBConfig expected, DBConfig actual) {}
}
