package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GeneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneAllPropertiesEquals(Gene expected, Gene actual) {
        assertGeneAutoGeneratedPropertiesEquals(expected, actual);
        assertGeneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneAllUpdatablePropertiesEquals(Gene expected, Gene actual) {
        assertGeneUpdatableFieldsEquals(expected, actual);
        assertGeneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneAutoGeneratedPropertiesEquals(Gene expected, Gene actual) {
        assertThat(expected)
            .as("Verify Gene auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneUpdatableFieldsEquals(Gene expected, Gene actual) {
        assertThat(expected)
            .as("Verify Gene relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneUpdatableRelationshipsEquals(Gene expected, Gene actual) {
        assertThat(expected)
            .as("Verify Gene relationships")
            .satisfies(e -> assertThat(e.getCuradoria()).as("check curadoria").isEqualTo(actual.getCuradoria()))
            .satisfies(e -> assertThat(e.getOrganismo()).as("check organismo").isEqualTo(actual.getOrganismo()));
    }
}
