package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganismoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoAllPropertiesEquals(Organismo expected, Organismo actual) {
        assertOrganismoAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganismoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoAllUpdatablePropertiesEquals(Organismo expected, Organismo actual) {
        assertOrganismoUpdatableFieldsEquals(expected, actual);
        assertOrganismoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoAutoGeneratedPropertiesEquals(Organismo expected, Organismo actual) {
        assertThat(expected)
            .as("Verify Organismo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoUpdatableFieldsEquals(Organismo expected, Organismo actual) {
        assertThat(expected)
            .as("Verify Organismo relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getSigla()).as("check sigla").isEqualTo(actual.getSigla()))
            .satisfies(e -> assertThat(e.getApelido()).as("check apelido").isEqualTo(actual.getApelido()))
            .satisfies(e -> assertThat(e.getSilhueta()).as("check silhueta").isEqualTo(actual.getSilhueta()))
            .satisfies(
                e -> assertThat(e.getSilhuetaContentType()).as("check silhueta contenty type").isEqualTo(actual.getSilhuetaContentType())
            )
            .satisfies(e -> assertThat(e.getIcone()).as("check icone").isEqualTo(actual.getIcone()))
            .satisfies(e -> assertThat(e.getPos()).as("check pos").isEqualTo(actual.getPos()))
            .satisfies(e -> assertThat(e.getImagem()).as("check imagem").isEqualTo(actual.getImagem()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganismoUpdatableRelationshipsEquals(Organismo expected, Organismo actual) {}
}
