package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProteinaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProteinaAllPropertiesEquals(Proteina expected, Proteina actual) {
        assertProteinaAutoGeneratedPropertiesEquals(expected, actual);
        assertProteinaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProteinaAllUpdatablePropertiesEquals(Proteina expected, Proteina actual) {
        assertProteinaUpdatableFieldsEquals(expected, actual);
        assertProteinaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProteinaAutoGeneratedPropertiesEquals(Proteina expected, Proteina actual) {
        assertThat(expected)
            .as("Verify Proteina auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProteinaUpdatableFieldsEquals(Proteina expected, Proteina actual) {
        assertThat(expected)
            .as("Verify Proteina relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getTamanho()).as("check tamanho").isEqualTo(actual.getTamanho()))
            .satisfies(e -> assertThat(e.getMassa()).as("check massa").isEqualTo(actual.getMassa()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProteinaUpdatableRelationshipsEquals(Proteina expected, Proteina actual) {
        assertThat(expected)
            .as("Verify Proteina relationships")
            .satisfies(e -> assertThat(e.getCuradoria()).as("check curadoria").isEqualTo(actual.getCuradoria()))
            .satisfies(e -> assertThat(e.getVersao()).as("check versao").isEqualTo(actual.getVersao()))
            .satisfies(e -> assertThat(e.getGene()).as("check gene").isEqualTo(actual.getGene()))
            .satisfies(e -> assertThat(e.getReferencias()).as("check referencias").isEqualTo(actual.getReferencias()))
            .satisfies(e -> assertThat(e.getRecursos()).as("check recursos").isEqualTo(actual.getRecursos()));
    }
}
