package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecursoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecursoAllPropertiesEquals(Recurso expected, Recurso actual) {
        assertRecursoAutoGeneratedPropertiesEquals(expected, actual);
        assertRecursoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecursoAllUpdatablePropertiesEquals(Recurso expected, Recurso actual) {
        assertRecursoUpdatableFieldsEquals(expected, actual);
        assertRecursoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecursoAutoGeneratedPropertiesEquals(Recurso expected, Recurso actual) {
        assertThat(expected)
            .as("Verify Recurso auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecursoUpdatableFieldsEquals(Recurso expected, Recurso actual) {
        assertThat(expected)
            .as("Verify Recurso relevant properties")
            .satisfies(e -> assertThat(e.getUid()).as("check uid").isEqualTo(actual.getUid()))
            .satisfies(e -> assertThat(e.getDb()).as("check db").isEqualTo(actual.getDb()))
            .satisfies(e -> assertThat(e.getLink()).as("check link").isEqualTo(actual.getLink()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecursoUpdatableRelationshipsEquals(Recurso expected, Recurso actual) {
        assertThat(expected)
            .as("Verify Recurso relationships")
            .satisfies(e -> assertThat(e.getProteinas()).as("check proteinas").isEqualTo(actual.getProteinas()));
    }
}
