package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReferenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferenciaAllPropertiesEquals(Referencia expected, Referencia actual) {
        assertReferenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertReferenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferenciaAllUpdatablePropertiesEquals(Referencia expected, Referencia actual) {
        assertReferenciaUpdatableFieldsEquals(expected, actual);
        assertReferenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferenciaAutoGeneratedPropertiesEquals(Referencia expected, Referencia actual) {
        assertThat(expected)
            .as("Verify Referencia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferenciaUpdatableFieldsEquals(Referencia expected, Referencia actual) {
        assertThat(expected)
            .as("Verify Referencia relevant properties")
            .satisfies(e -> assertThat(e.getCitacao()).as("check citacao").isEqualTo(actual.getCitacao()))
            .satisfies(e -> assertThat(e.getLink()).as("check link").isEqualTo(actual.getLink()))
            .satisfies(e -> assertThat(e.getAno()).as("check ano").isEqualTo(actual.getAno()))
            .satisfies(e -> assertThat(e.getAutores()).as("check autores").isEqualTo(actual.getAutores()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferenciaUpdatableRelationshipsEquals(Referencia expected, Referencia actual) {
        assertThat(expected)
            .as("Verify Referencia relationships")
            .satisfies(e -> assertThat(e.getProteinas()).as("check proteinas").isEqualTo(actual.getProteinas()));
    }
}
