package org.semprotdb.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VersaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersaoAllPropertiesEquals(Versao expected, Versao actual) {
        assertVersaoAutoGeneratedPropertiesEquals(expected, actual);
        assertVersaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersaoAllUpdatablePropertiesEquals(Versao expected, Versao actual) {
        assertVersaoUpdatableFieldsEquals(expected, actual);
        assertVersaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersaoAutoGeneratedPropertiesEquals(Versao expected, Versao actual) {
        assertThat(expected)
            .as("Verify Versao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersaoUpdatableFieldsEquals(Versao expected, Versao actual) {
        assertThat(expected)
            .as("Verify Versao relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDetalhes()).as("check detalhes").isEqualTo(actual.getDetalhes()))
            .satisfies(e -> assertThat(e.getRelease()).as("check release").isEqualTo(actual.getRelease()))
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getNumero()).as("check numero").isEqualTo(actual.getNumero()))
            .satisfies(e -> assertThat(e.getLogo()).as("check logo").isEqualTo(actual.getLogo()))
            .satisfies(e -> assertThat(e.getLog()).as("check log").isEqualTo(actual.getLog()))
            .satisfies(e -> assertThat(e.getTexto()).as("check texto").isEqualTo(actual.getTexto()))
            .satisfies(e -> assertThat(e.getImagem()).as("check imagem").isEqualTo(actual.getImagem()))
            .satisfies(e -> assertThat(e.getImagemContentType()).as("check imagem contenty type").isEqualTo(actual.getImagemContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersaoUpdatableRelationshipsEquals(Versao expected, Versao actual) {}
}
